### ISSUE TITLE
API Fetching inventories list with wrong credentials 

### ISSUE THREAD

**Issue by redhatHameed** [CrunchyData/crunchy-bridge-operator#25]
From DBaaS UI flow, the user entered the wrong credentials and still able to see the list of inventories 

![image](https://user-images.githubusercontent.com/41960152/130843900-2cbf1f4d-0ee9-4339-a61f-9fb89aa5b23c.png)

![image (1)](https://user-images.githubusercontent.com/41960152/130843884-698dd7aa-47f1-4185-8d88-5fe2f20a666a.png)

Steps:

1-The first-time user entered the correct credentials and successfully get the list of inventories.
2- in the next attempt, the user entered the wrong credentials information, on the UI and was still able to get the inventories list and able to connect with the database from UI.

**Comment by wilybrace** [comment]
After some interaction with the invalidation hooks that were added in #26 - it's clear that the operator is attempting to concurrently multiplex users through the API connection.

To support that, the invalidation method will not work because each session needs to exchange data with the API independently based on the credentials configured via the inventory object.

I will remove the invalidation methods in #26 and merge it to capture its content, but will create a new change set to offer the ability to have a per-client login manager. It would still be good from a resource management perspective to "clean up" before exiting the Reconcile function - likely through a `Close()` function call to borrow Go conventions.
