### ISSUE TITLE
Create Controllers and CRDs based on DBaaS operator design 

### ISSUE THREAD

**Issue by redhatHameed** [CrunchyData/crunchy-bridge-operator#7]
Based on the design diagram from the DBaaS operator, the CrunchyBridge operator required to create CRDs and Controllers for integration with the DBaaS operator.

![Screenshot from 2021-06-01 17-20-09](https://user-images.githubusercontent.com/41960152/120376076-728ddb80-c2e9-11eb-9039-4f3b0564097b.png)

*CRDs has shown in blue are required to defined by a CrunchyBridge operator*
*CRD spec and status will follow the same structure defined by the DBaaS operator*

**Comment by wilybrace** [comment]
I missed the diagram being attached to this issue.

In the mental model from which I'm working, the lower boxes would be enclosed in a grouping box labeling the "operator process" since the platform operator pattern and DBaaS operator patterns both exist within it.

For purposes of segregating responsibilities...
The platform operator:
* manages its own API object for the clusters
* expects a configuration object for the client credentials

The DBaaS operator:
* Creates the client credential object expected by the platform operator
* Queries for existing platform API objects and their statuses
* Updates the inventories and connections based on those statuses

Said differently, the platform operator concerns itself only with provisioning clusters in Crunchy Bridge and maintaining the API objects representing those clusters; the DBaaS operator concerns itself with the DBaaS functional requirements by reading and monitoring the API objects maintained by the platform operator.

If there's a mismatch here, would certainly be open to a call to resolve.

**Comment by wilybrace** [comment]
Based on a clarification call with redhatHameed:

The simplest statement is that the DBaaS operator on the block diagram represents the DBaaS operator running within the environment (source code living at github.com/RHEcosystemAppEng/dbaas-operator) and the Platform Operator block represents the "operator process" I mentioned in my previous comments.

Given that, the separation of concerns I described remains, but exists _within_ the Platform Operator block as the Crunchy Bridge Controller manages the Crunchy Bridge interaction and the DBaaS-* controller(s) handle DBaaS-specific patterns, such as those listed under the "DBaaS Operator" in the earlier comment.

**Comment by redhatHameed** [comment]
> Based on a clarification call with redhatHameed:
> 
> The simplest statement is that the DBaaS operator on the block diagram represents the DBaaS operator running within the environment (source code living at github.com/RHEcosystemAppEng/dbaas-operator) and the Platform Operator block represents the "operator process" I mentioned in my previous comments.
> 
> Given that, the separation of concerns I described remains, but exists _within_ the Platform Operator block as the Crunchy Bridge Controller manages the Crunchy Bridge interaction and the DBaaS-* controller(s) handle DBaaS-specific patterns, such as those listed under the "DBaaS Operator" in the earlier comment.

Thanks, @wilybrace in addition to as shown in diagram within Platform Operator under DBaaS Operator requirements :  

Create a RegistrationConfigMap which is used to inform the  ( [DBaaS operator](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/1cfd6ca87ee927bc8bd3adda0c3a53252df7dfb3/controllers/providers.go#L9))  issue #9

**Comment by redhatHameed** [comment]
Resolved in #8
